#!/bin/bash

# History
alias h='history'
alias hg='history | grep'
alias pg='ps aux | grep'

# File-system Traversal
alias b='cd ..'
alias bb='b;b'
alias bbb='b;b;b'
alias bbbb='b;b;b;b'
alias bbbbb='b;b;b;b;b'

alias bl='b;ls'
alias bbl='bb;ls'
alias bbbl='bbb;ls'
alias bbbbl='bbbb;ls'
alias bbbbbl='bbbbb;ls'

alias bll='b;ll'
alias bbll='bb;ll'
alias bbbll='bbb;ll'
alias bbbbll='bbbb;ll'
alias bbbbbll='bbbbb;ll'

alias home='cd ~/'

# ls aliases
alias ls='ls -G' # -G for mac color
alias l='ls -A'
alias ll='ls -Alh'
alias lt='ls -Alht'
alias lfs='ls -AlhrS --group-directories-first'

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

alias auto='~/linux-tools/bashrc/autoapp'

#function run
run() {
    number=$1
    shift
    for i in `seq $number`; do
      $@
    done
}

#alias ptop='top -p $(pidof $1 | tr ' ' ',')'
#alias ptop='top -p $(pidof $1 | tr '"'"' '"'"' '"'"','"'"')'
#function ptop() { top -p pidof "$@" | tr ' ' ','; }

# git aliases
alias mergemaster='git checkout master; git merge develop; git push origin master; git checkout develop'
alias push='git push origin develop --tags'
alias pull='git push origin master;git pull origin develop'
