#!/bin/bash

if [ $1 = "1" ]; then
	resize -s 64 238 > /dev/null
	#gnome-terminal --geometry=238x64+0+20
elif [ $1 = "2" ]; then
	resize -s 64 117 > /dev/null
	#gnome-terminal --geometry=117x64+0+20
	gnome-terminal --geometry=117x64+960+20
elif [ $1 = "3" ]; then
	resize -s 64 77 > /dev/null
	#gnome-terminal --geometry=77x64+0+20
	gnome-terminal --geometry=77x64+640+20
	gnome-terminal --geometry=77x64+1280+20
elif [ $1 = "4" ]; then
	resize -s 30 117 > /dev/null
	#gnome-terminal --geometry=117x30+0+20
	gnome-terminal --geometry=117x30+960+20
	gnome-terminal --geometry=117x31+0+620
	gnome-terminal --geometry=117x31+960+620
elif [ $1 = "6" ]; then
	resize -s 30 77 > /dev/null
	#gnome-terminal --geometry=77x30+0+20
	gnome-terminal --geometry=77x30+640+20
	gnome-terminal --geometry=77x30+1280+20
	gnome-terminal --geometry=77x31+0+620
	gnome-terminal --geometry=77x31+640+620
	gnome-terminal --geometry=77x31+1280+620
fi

exit
