#!/bin/bash

# ROS Hydro
sourceif /opt/ros/jade/setup.zsh
sourceif ~/catkin_ws/devel/setup.zsh

# ROS Network Config
export ROS_HOSTNAME=$(hostname)

# ROS Robot Aliases
alias use-mbot="export ROS_MASTER_URI=http://mecanumbot:11311"
alias use-rov="export ROS_MASTER_URI=http://bluerov:11311"
alias use-local="export ROS_MASTER_URI=http://localhost:11311"
