#!/bin/bash

# Django
alias drs1='python manage.py runserver 0.0.0.0:8001'
alias drs2='python manage.py runserver 0.0.0.0:8002'
alias drs3='python manage.py runserver 0.0.0.0:8003'
alias drs4='python manage.py runserver 0.0.0.0:8004'
alias drs5='python manage.py runserver 0.0.0.0:8005'
alias drs6='python manage.py runserver 0.0.0.0:8006'

# Flask Ext Script
alias frs1='python manage.py runserver -t 0.0.0.0 -p 7001'
alias frs2='python manage.py runserver -t 0.0.0.0 -p 7002'
alias frs3='python manage.py runserver -t 0.0.0.0 -p 7003'
alias frs4='python manage.py runserver -t 0.0.0.0 -p 7004'
alias frs5='python manage.py runserver -t 0.0.0.0 -p 7005'
alias frs6='python manage.py runserver -t 0.0.0.0 -p 7006'

# Vagrant
alias vup='vagrant up --provider=openstack'
alias vssh='vagrant ssh'
alias vdown='vagrant destroy'
alias vdev="vssh -c '/vagrant/deploy/dns-dev.sh'"
alias vprod="vssh -c '/vagrant/deploy/dns-prod.sh'"

# work
alias adb='python manage.py runserver -t 0.0.0.0 -p 7777'
